### ISSUE TITLE
cli.js is not working correctly.

### ISSUE THREAD

**Issue by artone** [LiamKarlMitchell/InfiniteSky#104]
Windows 7 64bit

charAt(1) would say wrong thing such as
````
#ping google.com
````
is a p when it should be #.
Obviously charAt(0) should be used.

Other commands such as /help do not work either.
Invalid regex.

**Comment by LiamKarlMitchell** [comment]
Confirmed

**Comment by LiamKarlMitchell** [comment]
\/(\w+)\s?(.*)?
