### ISSUE TITLE
Packet 52 shows status messages for things.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [LiamKarlMitchell/InfiniteSky#145]
Packet shows status messages so far.

````
52 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00
````

byte PacketID
int Code
???

Seems so far messages are from 64+ from the message.dat

| Code    | ID    | Message             |
| -----------|:-- |:----------------------------|
| 0 | 64 | Successful. |
| 1 | 65 | Item can not be enchanted any further. |
| 2 | 66 | Item can not be enchanted any further. |
| 3 | 26 36 | Not enough silver coins. |
| 4 | 39 | The item has been damaged. |
| 5 | 67 | Failed |

Must search more later :).

**Comment by Ane2** [comment]
Enchanting implemented in 100%
