### ISSUE TITLE
On character location save

### ISSUE THREAD

**Issue by Ane2** [LiamKarlMitchell/InfiniteSky#155]
We cannot round or floor the values, we want to keep the precision, because after character logs back in, is mostly above the ground or under - slightly.

**Comment by LiamKarlMitchell** [comment]
Sure, But the structure the server gives to the client is using an integer at login/character structure

**Comment by LiamKarlMitchell** [comment]
I think we can possibly find a way to save the location and location to into the database.
When the next socket connects we should confirm and set the location as the new location.
We send through int for inital character data struct but the action would get the float value.
