### ISSUE TITLE
account problem

### ISSUE THREAD

**Issue by projectt19** [LiamKarlMitchell/InfiniteSky#191]
i create a account from this link https://anrinch.com/create-an-account/ but i did not get any activation e-mail ? what is the problem help me please ?

**Comment by LiamKarlMitchell** [comment]
This is not the appropriate location.
It is best to Message the Facebook group or email support. 
Cmrayla@gmail.com please email them and tell them your web account email :).
Outlook/live/hotmail were ignoring our emails.
